### PR TITLE
WIP: Edits on section 3

### PR DESCRIPTION
**Pull request by jrising**

### CODE REVIEW

**Comment by atrisovic** [comment]
This PR will be tricky to merge because the changes are made to the `html` files (which are created from `content/***.md` files), in other words the changes should be moved to `md` files :/

**Comment by jrising** [comment]
I didn't hand-update the html files. I just re-generated the pages, and then checked in the result. Probably the right solution here is to remove the html files from the repo, since they won't be able to be easily merged.

In the meantime, I'll just revert the changes to these files.

**Comment by jrising** [comment]
I'm also going to close this, because it should not be merged until Azhar has edited it.

**Comment by atrisovic** [comment]
Ah, ok that's great. 
There is quite a bit of new text, it would be shame if we forgot about it.
I will reopen the PR and just mark it as WIP.

**Comment by atrisovic** [comment]
One thing to do is:

- [ ] move `_site/content/reduced-form-specification.md` to `content/reduced-form-specification.md`

**Pull request merged**
