### PR TITLE
Add example of map visualizations

### PR DESCRIPTION
**Pull request by jrising**
Shows both the easy and complicated version of how things can work.

### CODE REVIEW

**Comment by jrising** [comment]
@azharhsain I wish you wouldn't keep doing that. I asked @atrisovic to review because she has a better sense of how to get the most out of the JupyterBook system.

**Comment by azharhsain** [comment]
@jrising Really sorry! Won't happen again.

**Comment by atrisovic** [comment]
I think it looks very pretty!

I saw this page with examples (in the official guide):
https://jupyterbook.org/features/notebooks.html

the whole page is actually a jupyter notebook:
https://github.com/jupyter/jupyter-book/blob/master/jupyter_book/book_template/content/features/notebooks.ipynb

In case you created the plots as jupyter notebook, we could save them like that and add them as a new page in the book (but it's not a big difference in how it's seen in the book).

**Comment by jrising** [comment]
That's a good point-- that we can have these generated automatically. I'm going to leave it alone for now, but that's a good idea for the future.

**Pull request merged**
